[tool.poetry]
name = "depth-estimation"
version = "0.1.0"
description = "Depth estimation using ZoeDepth model with FastAPI and Gradio interfaces."
authors = ["Gökay Meydan"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.116.1"
uvicorn = "^0.35.0"
torch = "^2.7.1"
torchvision = "^0.22.1"
gradio = "^5.38.0"
python-dotenv = "^1.1.1"
requests = "^2.32.4"
pillow = "^11.3.0"
aiofiles = "^24.1.0"
python-multipart = "^0.0.20"

# tools for development
matplotlib = "^3.10.7"
scipy = "^1.16.2"
timm = "0.6.7"
[tool.poetry.group.dev.dependencies]
black = "^25.1.0"
isort = "^6.0.1"
ruff = "^0.12.4"
safety = "^3.6.0"
pytest = "^8.2.2" # for test

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"